// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntumqasyohfuhstkhpvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dW1xYXN5b2hmdWhzdGtocHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTU1NDgsImV4cCI6MjA2Nzg3MTU0OH0.b7S7vSbSfjiiLnO_s5QX9D1aGgMyBQ-3ihpW-RzRGvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});